name: synnet
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9.*
  - pytorch
  - torchvision
  - pytorch-cuda=11.7
  - pytorch-lightning
  - rdkit=2022.03.*
  - datamol
  - pytdc<0.3.8 # https://github.com/mims-harvard/TDC/issues/180
  - scikit-learn>=1.1.*
  - numba
  - ipykernel
  - ipywidgets # Silence warning, see https://github.com/tqdm/tqdm/issues/187
  - nb_conda_kernels
  - pre-commit
  - black=22.6.*
  - black-jupyter=22.6.*
  - isort=5.10.*
  - pytest
  - pip
  - pip:
    - setuptools==59.5.0 # https://github.com/pytorch/pytorch/issues/69894
    - pathos
    - rich
    - pyyaml
    - fcd_torch # for evaluators in pytdc
    - wandb
    - tabulate # for df.to_markdown()
    
  #From chrulm/synnet fork
